# Generated by Django 3.2.9 on 2022-02-20 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Записи', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок урока'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Предмет')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('time_lesson', models.DateTimeField(verbose_name='Время на выполнение')),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
